name: res_ecommerce
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  sizer: ^2.0.15
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.2
  flutter_svg: ^1.1.5
  lottie: ^1.4.3
  equatable: ^2.0.5
  rename: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/logo.png"
    min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf